"""add attemps and last error to manifest

Revision ID: 5fb1553b6b46
Revises: cf706d1d9217
Create Date: 2026-10-01 10:07:50.036924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb1553b6b46'
down_revision: Union[str, Sequence[str], None] = 'cf706d1d9217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbt_manifest',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False), nullable=False),
    sa.Column('raw_table_name', sa.String(), nullable=False),
    sa.Column('staging_table_name', sa.String(), nullable=False),
    sa.Column('raw_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dbt_ingested_status', sa.String(), nullable=False),
    sa.Column('dbt_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attemps', sa.Integer(), server_default=sa.text('0::int'), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_table_name', 'raw_ingested_at', name='uq_dbt_manifest'),
    schema='ctl'
    )
    op.drop_table('my_first_dbt_model', schema='analytics')
    op.add_column('api_extraction_manifest', sa.Column('attemps', sa.Integer(), server_default=sa.text('0::int'), nullable=False), schema='ctl')
    op.add_column('api_extraction_manifest', sa.Column('last_error', sa.String(), nullable=True), schema='ctl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_extraction_manifest', 'last_error', schema='ctl')
    op.drop_column('api_extraction_manifest', 'attemps', schema='ctl')
    op.create_table('my_first_dbt_model',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    schema='analytics'
    )
    op.drop_table('dbt_manifest', schema='ctl')
    # ### end Alembic commands ###
