"""add some columns

Revision ID: 6ad62e890427
Revises: b9f1c36fd49d
Create Date: 2026-09-24 16:25:18.904049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ad62e890427'
down_revision: Union[str, Sequence[str], None] = 'b9f1c36fd49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_extraction_manifest', sa.Column('id', sa.BIGINT(), sa.Identity(always=False), nullable=False), schema='ctl')
    op.add_column('api_extraction_manifest', sa.Column('api_extracted_at', sa.DateTime(timezone=True), nullable=False), schema='ctl')
    op.create_unique_constraint('uq_extraction_manifest', 'api_extraction_manifest', ['location'], schema='ctl')
    op.drop_column('api_extraction_manifest', 'extracted_at', schema='ctl')
    op.add_column('api_rate_limiter', sa.Column('id', sa.BIGINT(), sa.Identity(always=False), nullable=False), schema='ctl')
    op.create_unique_constraint('uq_rate_limiter', 'api_rate_limiter', ['api_name', 'window_start'], schema='ctl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rate_limiter', 'api_rate_limiter', schema='ctl', type_='unique')
    op.drop_column('api_rate_limiter', 'id', schema='ctl')
    op.add_column('api_extraction_manifest', sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='ctl')
    op.drop_constraint('uq_extraction_manifest', 'api_extraction_manifest', schema='ctl', type_='unique')
    op.drop_column('api_extraction_manifest', 'api_extracted_at', schema='ctl')
    op.drop_column('api_extraction_manifest', 'id', schema='ctl')
    # ### end Alembic commands ###
