"""add tz to rate limiter table

Revision ID: 723e97ff48a3
Revises: 91b0d4d2f0c0
Create Date: 2026-09-23 15:36:26.343379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '723e97ff48a3'
down_revision: Union[str, Sequence[str], None] = '91b0d4d2f0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_rate_limiter', 'window_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='ctl', 
               postgresql_using=f"window_start AT TIME ZONE 'UTC'",)
    op.alter_column('api_rate_limiter', 'window_reset_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='ctl', 
               postgresql_using=f"window_reset_at AT TIME ZONE 'UTC'",)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_rate_limiter', 'window_reset_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='ctl')
    op.alter_column('api_rate_limiter', 'window_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='ctl')
    # ### end Alembic commands ###
