"""add params to apiextratctionmanifest

Revision ID: 8fdfa1851f3a
Revises: 6ad62e890427
Create Date: 2026-09-28 17:48:00.696233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fdfa1851f3a'
down_revision: Union[str, Sequence[str], None] = '6ad62e890427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_extraction_manifest', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False), schema='ctl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_extraction_manifest', 'params', schema='ctl')
    # ### end Alembic commands ###
