"""add first control table

Revision ID: 91b0d4d2f0c0
Revises: 
Create Date: 2026-09-18 18:05:30.040482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91b0d4d2f0c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("create schema ctl")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_rate_limiter',
    sa.Column('api_name', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_reset_at', sa.DateTime(), nullable=False),
    sa.Column('limit_total', sa.Integer(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('api_name', 'window_start'),
    schema='ctl'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("drop schema ctl")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_rate_limiter', schema='ctl')
    # ### end Alembic commands ###
