"""add dag_name to manifest

Revision ID: cf706d1d9217
Revises: 8fdfa1851f3a
Create Date: 2026-09-29 14:48:02.053890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf706d1d9217'
down_revision: Union[str, Sequence[str], None] = '8fdfa1851f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_extraction_manifest', sa.Column('dag_name', sa.String(), nullable=False), schema='ctl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_extraction_manifest', 'dag_name', schema='ctl')
    # ### end Alembic commands ###
